apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: AUTHORIZATION_ISSUER_URI
          value: https://dev-697175.okta.com/oauth2/default
        - name: CLIENT_ID
          value: 0oa35a16zxMyF9QXk4x6
        - name: CLIENT_SECRET
          value: 1ZUsLj2hK66pKyx2Irqock0TkaiaL9UQJO1fIBKk
        - name: MONGODB_URI
          value: mongodb://mongoUser:secret@mongo:27017
        - name: PORT
          value: "3000"
        - name: SCOPE
          value: orders-api
        image: app
        name: orders-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
