apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: orders-api-test
  name: orders-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-api-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders-api-test
    spec:
      containers:
      - image: avegaaida/orders-api-test:latest
        name: orders-api-test
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "125Mi"
          requests:
            cpu: "0.25"
            memory: "25Mi"
        env:
          - name: MONGODB_URI
            value: "mongodb+srv://testDbUser:mxnROwuOZ9HpllKD@cluster0-wojvy.mongodb.net/test?retryWrites=true&w=majority"
          - name: AUTHORIZATION_ISSUER_URI
            value: "https://dev-697175.okta.com/oauth2/default"
          - name: CLIENT_ID
            value: "0oa35a16zxMyF9QXk4x6"
          - name: CLIENT_SECRET
            value: "1ZUsLj2hK66pKyx2Irqock0TkaiaL9UQJO1fIBKk"
          - name: SCOPE
            value: "orders-api"