apiVersion: v1
kind: Service
metadata:
  name: my-orders-api
  labels:
    app: my-orders-api
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: orders-api-test
  type: LoadBalancer