version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.1

      - image: mongo:4.0.18-xenial
        environment:
          MONGO_INITDB_DATABASE: test
          MONGO_INITDB_ROOT_USERNAME: mongoUser
          MONGO_INITDB_ROOT_PASSWORD: secret      
        command: [mongod, --smallfiles]
    machine: true        
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: Wait for Mongo to start
          command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s        

      - run: npm install
      - run: npm test

      - run:
          name: Build and push Docker image
          command: |
            docker build -t avegaaida/orders-api-test:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push avegaaida/orders-api-test:$TAG

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master