version: 2.1

orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.1

      - image: mongo:4.0.18-xenial
        environment:
          MONGO_INITDB_DATABASE: test
          MONGO_INITDB_ROOT_USERNAME: mongoUser
          MONGO_INITDB_ROOT_PASSWORD: secret      
        command: [mongod, --smallfiles]
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV      
      - run:
          name: Wait for Mongo to start
          command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s        

      - run: npm install
      - run: npm test

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            docker build -t avegaaida/orders-api-test:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker tag avegaaida/orders-api-test:$TAG avegaaida/orders-api-test:latest
            docker push avegaaida/orders-api-test:$TAG
  deploy:
    executor: azure-aks/default
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: k8s-test
          resource-group: k8s-test
          install-kubectl: true
          perform-login: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: kubernetes-orders-api.yaml
          resource-name: my-orders-api
          show-kubectl-command: true

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only: master